# Generated by Django 5.1.4 on 2024-12-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedtemplate',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
    ]
