# Generated by Django 5.1.4 on 2024-12-29 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeds', '0002_embedtemplate_multiple'),
        ('projects', '0003_tagcategory_tag'),
        ('testimonials', '0002_remove_testimonial_images_remove_testimonial_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embed_instances', to='projects.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embed_instances', to='embeds.embedtemplate')),
                ('testimonials', models.ManyToManyField(related_name='embed_instances', to='testimonials.testimonial')),
            ],
        ),
    ]
