# Generated by Django 5.1.4 on 2024-12-29 02:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeds', '0003_embedinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
