# Generated by Django 5.1.4 on 2025-01-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeds', '0004_alter_embedinstance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedinstance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='embedinstance',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
