# Generated by Django 5.1.4 on 2025-01-03 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeds', '0005_embedinstance_description_embedinstance_name'),
        ('testimonials', '0002_remove_testimonial_images_remove_testimonial_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedinstance',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embed_instances', to='embeds.embedtemplate'),
        ),
        migrations.AlterField(
            model_name='embedinstance',
            name='testimonials',
            field=models.ManyToManyField(blank=True, related_name='embed_instances', to='testimonials.testimonial'),
        ),
    ]
