# Generated by Django 5.1.4 on 2025-01-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeds', '0006_alter_embedinstance_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedinstance',
            name='backgroundColor',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='embedinstance',
            name='fontFamily',
            field=models.CharField(default='Arial', max_length=255),
        ),
        migrations.AddField(
            model_name='embedinstance',
            name='primaryColor',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
