# Generated by Django 5.1.4 on 2025-01-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeds', '0007_embedinstance_backgroundcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedinstance',
            name='callToActionLabel',
            field=models.CharField(blank=True, default='Visit', max_length=255),
        ),
        migrations.AddField(
            model_name='embedinstance',
            name='callToActionUrl',
            field=models.URLField(blank=True, default='https://www.99testimonials.com'),
        ),
    ]
