# Generated by Django 5.1.4 on 2025-01-20 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('product_id', models.CharField(blank=True, max_length=128)),
                ('testimonials', models.IntegerField(default=15)),
                ('video_testimonials', models.IntegerField(default=1)),
                ('campaigns', models.IntegerField(default=1)),
                ('projects', models.IntegerField(default=1)),
                ('staff', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('payment_link', models.URLField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
