# Generated by Django 5.1.4 on 2025-03-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
