# Generated by Django 5.1.4 on 2025-03-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_brandlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandlogo',
            name='image',
            field=models.ImageField(upload_to='brand_logos/'),
        ),
    ]
