# Generated by Django 5.1.4 on 2025-03-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_brandlogo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hex_code', models.CharField(max_length=7)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_colors', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='BrandFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_fonts', to='projects.project')),
            ],
        ),
    ]
