# Generated by Django 5.1.4 on 2025-03-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_brandcolor_brandfont'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandfont',
            name='font_weight',
            field=models.CharField(default='400', max_length=5),
        ),
    ]
