# Generated by Django 5.1.4 on 2025-02-14 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('wall_of_love', 'Wall of Love'), ('widgets', 'Widgets'), ('pop_ups', 'Pop-ups'), ('images', 'Images'), ('videos', 'Videos'), ('video_embeds', 'Video Embeds')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='templates/')),
                ('variables', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('variables', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displays.template')),
            ],
        ),
    ]
