# Generated by Django 5.1.4 on 2025-02-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0002_alter_display_id'),
        ('testimonials', '0013_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='testimonials',
            field=models.ManyToManyField(related_name='displays', to='testimonials.testimonial'),
        ),
    ]
