# Generated by Django 5.1.4 on 2025-03-05 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0003_display_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='display',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
