# Generated by Django 5.1.4 on 2025-03-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0004_display_created_display_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='displays/'),
        ),
    ]
