# Generated by Django 5.1.7 on 2025-03-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0005_display_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='custom_subdomain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
