# Generated by Django 5.1.7 on 2025-04-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0006_display_custom_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='multiple',
            field=models.BooleanField(default=True),
        ),
    ]
