# Generated by Django 5.1.7 on 2025-04-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0007_template_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='branding',
            field=models.BooleanField(default=False),
        ),
    ]
