# Generated by Django 5.1.4 on 2025-01-20 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='pricing_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.pricingplan'),
            preserve_default=False,
        ),
    ]
