# Generated by Django 5.1.4 on 2024-12-25 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_tagcategory_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='campaign_logos/')),
                ('primaryColor', models.CharField(default='#000000', max_length=7)),
                ('backgroundColor', models.CharField(default='#ffffff', max_length=7)),
                ('fontFamily', models.CharField(default='Arial', max_length=255)),
                ('welcomeTitle', models.CharField(blank=True, default='', max_length=255)),
                ('welcomeNote', models.TextField(blank=True, default='')),
                ('textCheckbox', models.BooleanField(default=False)),
                ('videoCheckbox', models.BooleanField(default=False)),
                ('textButtonName', models.CharField(blank=True, default='', max_length=255)),
                ('videoButtonName', models.CharField(blank=True, default='', max_length=255)),
                ('responseTitle', models.CharField(blank=True, default='', max_length=255)),
                ('responseInstructions', models.TextField(blank=True, default='')),
                ('collectStarRating', models.BooleanField(default=False)),
                ('collectImageFiles', models.BooleanField(default=False)),
                ('gatherEmailEnabled', models.BooleanField(default=False)),
                ('gatherEmailRequired', models.BooleanField(default=False)),
                ('captureJobTitleEnabled', models.BooleanField(default=False)),
                ('captureJobTitleRequired', models.BooleanField(default=False)),
                ('collectUserPhotoEnabled', models.BooleanField(default=False)),
                ('collectUserPhotoRequired', models.BooleanField(default=False)),
                ('acquireWebsiteUrlEnabled', models.BooleanField(default=False)),
                ('acquireWebsiteUrlRequired', models.BooleanField(default=False)),
                ('gatherCompanyLogoEnabled', models.BooleanField(default=False)),
                ('gatherCompanyLogoRequired', models.BooleanField(default=False)),
                ('thankYouTitle', models.CharField(blank=True, default='', max_length=255)),
                ('thankYouNote', models.TextField(blank=True, default='')),
                ('callToActionEnabled', models.BooleanField(default=False)),
                ('callToActionLabel', models.CharField(blank=True, default='', max_length=255)),
                ('callToActionUrl', models.URLField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='projects.project')),
            ],
        ),
    ]
