# Generated by Django 5.1.4 on 2024-12-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='shareForm',
            field=models.BooleanField(default=True),
        ),
    ]
