# Generated by Django 5.1.4 on 2024-12-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_shareform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='shareForm',
            new_name='shareLink',
        ),
        migrations.AddField(
            model_name='campaign',
            name='shareFacebook',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='shareInstagram',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='shareLinkedin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='shareTiktok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='shareTwitter',
            field=models.BooleanField(default=True),
        ),
    ]
