# Generated by Django 5.1.4 on 2025-01-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_rename_shareform_campaign_sharelink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='removeBranding',
            field=models.BooleanField(default=True),
        ),
    ]
