# Generated by Django 5.1.4 on 2025-02-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_removebranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='videoResponseInstructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='videoResponseTitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
