# Generated by Django 5.1.4 on 2025-02-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_videoresponseinstructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='textResponseActionName',
            field=models.CharField(blank=True, default='Submit', max_length=255),
        ),
    ]
