# Generated by Django 5.1.4 on 2025-02-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_textresponseactionname'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='captureCompanyName',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='captureCompanyNameRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='customerDetailsTitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='shareWhatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='videoCollectImageFiles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='videoCollectStarRating',
            field=models.BooleanField(default=False),
        ),
    ]
