# Generated by Django 5.1.4 on 2025-02-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaign_capturecompanyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='textColor',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
