# Generated by Django 5.1.4 on 2025-01-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_testimonial_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='testimonials', to='testimonials.tag'),
        ),
    ]
