# Generated by Django 5.1.4 on 2025-01-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0005_alter_testimonial_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
