# Generated by Django 5.1.4 on 2025-02-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='source',
            field=models.CharField(blank=True, default='Text', max_length=32),
        ),
    ]
