# Generated by Django 5.1.4 on 2025-02-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0008_testimonial_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='source',
            field=models.CharField(blank=True, default='Import', max_length=32),
        ),
    ]
