# Generated by Django 5.1.4 on 2025-02-08 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0009_alter_testimonial_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testimonials.customer'),
        ),
    ]
