# Generated by Django 5.1.4 on 2025-02-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0010_testimonial_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customer_avatars/'),
        ),
    ]
