# Generated by Django 5.1.4 on 2025-02-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0011_customer_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='company_name',
            new_name='company',
        ),
    ]
