# Generated by Django 5.1.4 on 2025-02-10 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0012_rename_company_name_customer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
