# Generated by Django 5.1.4 on 2025-03-14 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0013_alter_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='testimonials.testimonial')),
            ],
        ),
    ]
