# Generated by Django 5.1.7 on 2025-04-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_campaign_custom_subdomain_campaign_last_checked_at_and_more'),
        ('testimonials', '0014_testimonialhighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='campaign',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign'),
        ),
    ]
