# Generated by Django 5.1.7 on 2025-04-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0015_testimonial_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='campaign',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='campaignId',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
